In [5]:
import pandas as pd
import torch
data_folder = "/biodata/nyanovsky/datasets/dti/processed/v2"
nodes = pd.read_csv(f"{data_folder}/node_df.csv")
edges = pd.read_csv(f"{data_folder}/edge_df.csv")

tensor_df = pd.read_csv(f"{data_folder}/dti_tensor_df.csv", index_col=0)


full_dataset = torch.load(f"{data_folder}/dti_full_dataset.pt")

In [6]:
nodes.head()

,node_id,ChG_deg,ChCh_deg,GG_deg,total_deg,node_type,louvain community (nodetype subgraph)
0,C155831,1,4,0,5,chem,141
1,G5243,41,0,17,58,gene,42
2,C24762158,9,2,0,11,chem,489
3,G213,85,0,3,88,gene,2
4,G506,6,0,3,9,gene,93

In [7]:
edges.head()

,src_id,trgt_id,edge_type,src_node_type,trgt_node_type,src_node_index,trgt_node_index
0,C155831,G5243,chg,chem,gene,0,1
1,C24762158,G213,chg,chem,gene,2,3
2,C24762158,G506,chg,chem,gene,2,4
3,C24762158,G563,chg,chem,gene,2,5
4,C24762158,G13884,chg,chem,gene,2,6

In [8]:
tensor_df.head()

      node_id  ChG_deg  ChCh_deg  GG_deg  total_deg node_type  tensor_index
0     C155831        1         4       0          5      chem             0
2   C24762158        9         2       0         11      chem             1
12  C54692492        3        10       0         13      chem             2
16  C12968471        8         0       0          8      chem             3
25  C24836820        1        23       0         24      chem             4