In [1]:
import pandas as pd
import torch
data_folder = "/biodata/nyanovsky/datasets/dti/processed/v2/"
nodes = pd.read_csv(f"{data_folder}node_df.csv", index_col="node_id")
edges = pd.read_csv(f"{data_folder}edge_df_dedup.csv")

tensor_df = pd.read_csv(f"{data_folder}dti_tensor_df.csv", index_col=0)


full_dataset = torch.load(f"{data_folder}dti_full_dataset.pt")

In [2]:
nodes.head()

,ChG_deg,ChCh_deg,GG_deg,total_deg,node_type,louvain community (nodetype subgraph)
node_id,,,,,,
C155831,1,4,0,5,chem,141
G5243,41,0,17,58,gene,42
C24762158,9,2,0,11,chem,489
G213,85,0,3,88,gene,2
G506,6,0,3,9,gene,93

In [3]:
edges.head()

,src_id,trgt_id,edge_type,src_node_type,trgt_node_type,src_node_index,trgt_node_index
0,C155831,G5243,chg,chem,gene,0,1
1,C24762158,G213,chg,chem,gene,2,3
2,C24762158,G506,chg,chem,gene,2,4
3,C24762158,G563,chg,chem,gene,2,5
4,C24762158,G13884,chg,chem,gene,2,6

In [4]:
import sys
sys.path.append("..")
from models.training_utils import load_feature_dict
from data_class import GNNData

In [5]:
data = GNNData(node_path="/biodata/nyanovsky/datasets/dti/processed/v2/node_df.csv",
               edge_path="/biodata/nyanovsky/datasets/dti/processed/v2/edge_df_dedup.csv",
               node_index_col="node_id",
               src_edge_col="src_id",
               dst_edge_col="trgt_id",
               node_type_col="node_type",
               edge_type_col="edge_type",
               src_node_type_col="src_node_type",
               dst_node_type_col="trgt_node_type")

Feture initialization already worked okay. If unsure, test it by checking that the features were assigned correctly to their nodes using the node_mapping attribute (i.e, get feature for node "A", and check if feature for index node_mapping["A"] is equal to it)

In [6]:
gene_feature_dict = load_feature_dict(data_folder+"prot_features_64.txt", data_folder+"prot_features_ids.txt", 
                                                    tensor_df, "gene")
data.initialize_features(64, gene_feature_dict, inplace=True)

/usr/users/nyanovsky/tesis/gnn_interface/data_class.py:171: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data_object.data[nodetype].x[tensor_idxs] = nodetype_embs

Check if PyG gets degrees right (against degrees that came from NetworkX)

In [7]:
print(data.data["gene"].degrees_by_edge_type[("chem", "chg", "gene")][:10])
print(data.data["chem"].degrees_by_edge_type[("chem", "chg", "gene")][:10])

tensor([41., 85.,  6.,  4.,  1.,  2.,  3.,  8., 19.,  3.])
tensor([1., 9., 3., 8., 1., 1., 2., 1., 2., 2.])

In [8]:
print(full_dataset["gene"]["degree_chg"][:10])
print(full_dataset["chem"]["degree_chg"][:10])
# Old dataset, degrees came from nx

[41 85  6  4  1  2  3  8 19  3]
[1 9 3 8 1 1 2 1 2 2]

In [9]:
from models.training_utils import NegativeSampler 

supervision_edge_type = ("chem", "chg", "gene")
src_degs = data.data["chem"].degrees_by_edge_type[supervision_edge_type]
dst_degs = data.data["gene"].degrees_by_edge_type[supervision_edge_type]

sampler = NegativeSampler(data.data, supervision_edge_type, src_degs, dst_degs)

In [10]:
from torch_geometric import seed_everything
seed_everything(42)
train_data, val_data, test_data = data.split_data(task="link_prediction",
                                                  negative_sampler=sampler,
                                                  supervision_edge_type=supervision_edge_type,
                                                  disjoint_train_ratio=0.2, 
                                                  num_val=0.1,
                                                  num_test=0.1)

/usr/users/nyanovsky/tesis/gnn_interface/../models/training_utils.py:183: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  probs = torch.tensor(self.weights[src_or_dst]**0.75)

Test if split works as expected

In [11]:
def test_equal_num_edges(dataset, sup_edge_type):
    num_chg_r = dataset[sup_edge_type
                        ]["edge_index"].shape[1]
    num_chg_l = dataset[(sup_edge_type[2], "rev_"+sup_edge_type[1], sup_edge_type[0])
                        ]["edge_index"].shape[1]
    print(
        f"num chg edges in both directions is equal: {num_chg_r == num_chg_l}")
    
def test_is_correct_p(dataset, sup_edge_type, p, total_num, prev_edges, is_train):
    # num_supervision divided by 2 because the same number of edges is generated as negative samples.
    # These are directed (i.e, a single link in one direction)
    num_supervision = dataset[sup_edge_type]["edge_label"].shape[0]
    if not is_train:
        num_supervision /=2

    
    num_msg = dataset[sup_edge_type
                      ]["edge_index"].shape[1]

    num = round(num_supervision + num_msg)
    expected_num = round(p*total_num + prev_edges)
    print(f"Is expected % of edges: {num == expected_num}")
    print(f"Expected {expected_num}, is {num}")

In [12]:
total_num_chg = data.data[supervision_edge_type]["edge_index"].shape[1]

datasets = {"train":train_data, "validation":val_data, "test":test_data}
percentage = [0.8,0.1,0.1]

prev_edges = 0
for name, p in zip(list(datasets.keys()), percentage):
    print(name + ":")
    test_equal_num_edges(datasets[name], supervision_edge_type)
    test_is_correct_p(datasets[name], supervision_edge_type, p, total_num_chg, prev_edges, name=="train")
    print("\n")

    num_sup_edges = datasets[name][supervision_edge_type]["edge_label"].shape[0]
    num_msg_edges = datasets[name][supervision_edge_type]["edge_index"].shape[1]
    if name !="train":
        num_sup_edges /= 2
        # no neg edges on train data, sampled on the fly while training

    prev_edges = round(num_sup_edges+num_msg_edges)

train:
num chg edges in both directions is equal: True
Is expected % of edges: True
Expected 30713, is 30713


validation:
num chg edges in both directions is equal: True
Is expected % of edges: True
Expected 34552, is 34552


test:
num chg edges in both directions is equal: True
Is expected % of edges: True
Expected 38391, is 38391

In [13]:
import yaml
configs_folder = "/biodata/nyanovsky/datasets/dti/best_models/"
with open(configs_folder+"sage_config.yaml","r") as file:
    sage_config = yaml.safe_load(file)

In [14]:
sage_config

{'conv': {'aggr': 'max'},
 'gral': {'L2_norm': False,
  'batch_norm': False,
  'dropout': 0.0,
  'hidden_channels': 32,
  'layer_connectivity': 'False',
  'macro_aggregation': 'sum',
  'msg_passing_layers': 4,
  'normalize_output': False,
  'post_process_layers': 0,
  'pre_process_layers': 0},
 'train': {'delta': 0.1,
  'epochs': 500,
  'feature_dim': 128,
  'features': 'go2vec',
  'lr': 0.01,
  'patience': 10,
  'weight_decay': 0.001}}

In [15]:
sage_config["train"].pop("epochs")
sage_config["train"].pop("feature_dim")
sage_config["train"].pop("features")

'go2vec'

In [16]:
sage_config

{'conv': {'aggr': 'max'},
 'gral': {'L2_norm': False,
  'batch_norm': False,
  'dropout': 0.0,
  'hidden_channels': 32,
  'layer_connectivity': 'False',
  'macro_aggregation': 'sum',
  'msg_passing_layers': 4,
  'normalize_output': False,
  'post_process_layers': 0,
  'pre_process_layers': 0},
 'train': {'delta': 0.1, 'lr': 0.01, 'patience': 10, 'weight_decay': 0.001}}

Test model with single split

In [17]:
from model_class import LinkPredictor

model = LinkPredictor(conv_name="SAGE",
                      gral_params=sage_config["gral"],
                      conv_params=sage_config["conv"],
                      optimizer_params=sage_config["train"])

In [18]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
splits = {"train":train_data, "val":val_data, "test":test_data}
model.train(splits, sampler,supervision_edge_type, epochs=500)

{'train_loss': [0.6843099594116211,
  4.635708332061768,
  0.9613096714019775,
  0.707546591758728,
  0.6849134564399719,
  0.6995795369148254,
  0.680513322353363,
  0.669815182685852,
  0.6658753156661987,
  0.6519668698310852,
  0.6495211720466614,
  0.6246516108512878,
  0.6060360670089722,
  0.5776278376579285,
  0.5609737038612366,
  0.56667160987854,
  0.5319799184799194,
  0.5282571911811829,
  0.5186967253684998,
  0.5145243406295776,
  0.49914056062698364,
  0.4877128601074219,
  0.4825231730937958,
  0.4776168167591095,
  0.47365719079971313,
  0.4585306942462921,
  0.4534991979598999,
  0.44336098432540894,
  0.43758586049079895,
  0.4350123405456543,
  0.42401760816574097,
  0.42219868302345276,
  0.41818967461586,
  0.41503143310546875,
  0.40352264046669006,
  0.40424275398254395,
  0.39672577381134033,
  0.3937200903892517,
  0.38627246022224426,
  0.38997969031333923,
  0.37977492809295654,
  0.38504427671432495,
  0.3968793749809265,
  0.37249723076820374,
  0.3762813210487366,
  0.38108351826667786,
  0.3724713921546936,
  0.37151622772216797,
  0.36708366870880127,
  0.3646547198295593,
  0.3629501461982727,
  0.35543105006217957,
  0.3615306615829468,
  0.35345378518104553,
  0.352755069732666,
  0.34908151626586914,
  0.34949609637260437,
  0.34753867983818054,
  0.34141185879707336,
  0.3423696756362915,
  0.34041181206703186,
  0.34146708250045776,
  0.33851033449172974,
  0.33362138271331787,
  0.3353237807750702,
  0.3329140841960907,
  0.3318878710269928,
  0.33532559871673584,
  0.3298587203025818,
  0.3282916843891144,
  0.32553210854530334,
  0.3249823749065399,
  0.3308669924736023,
  0.32758909463882446,
  0.33344775438308716,
  0.3260320723056793,
  0.3218929171562195,
  0.32410627603530884,
  0.32097819447517395,
  0.3264605700969696,
  0.31663990020751953,
  0.3164811432361603,
  0.32161590456962585,
  0.31529340147972107,
  0.31435540318489075,
  0.3072502315044403,
  0.3111560344696045,
  0.3079603910446167,
  0.3055552840232849,
  0.3070392310619354,
  0.30291473865509033,
  0.2993292510509491,
  0.30168280005455017,
  0.2969578504562378,
  0.30182185769081116,
  0.2985304594039917,
  0.2982538640499115,
  0.30253392457962036,
  0.3187992572784424,
  0.329281747341156,
  0.30723556876182556,
  0.3205661177635193,
  0.3075178563594818,
  0.3077987730503082,
  0.3080022931098938,
  0.3038024604320526,
  0.3010067641735077,
  0.2990570664405823,
  0.291616827249527,
  0.3073120415210724,
  0.29283154010772705,
  0.2997000813484192,
  0.29155072569847107,
  0.2916414141654968,
  0.2798375189304352,
  0.2856893837451935,
  0.28240591287612915,
  0.2872670590877533,
  0.2848462164402008,
  0.2856813371181488,
  0.2819317579269409,
  0.2774467468261719,
  0.2804538309574127,
  0.27886098623275757,
  0.2760402262210846,
  0.27759850025177,
  0.27747029066085815,
  0.2796995937824249,
  0.27332884073257446,
  0.27139967679977417,
  0.26951077580451965,
  0.27711746096611023,
  0.2743895351886749,
  0.27976784110069275,
  0.2703534960746765,
  0.2798665463924408,
  0.28603774309158325,
  0.2839663624763489,
  0.2736574113368988,
  0.28046488761901855,
  0.27729034423828125,
  0.28401732444763184,
  0.2735128700733185,
  0.27699294686317444,
  0.2786489427089691,
  0.2691752314567566,
  0.2735671401023865,
  0.2664174437522888,
  0.26994287967681885,
  0.26120010018348694,
  0.26487070322036743,
  0.2651457190513611,
  0.2596883177757263,
  0.26221221685409546,
  0.2603297531604767,
  0.2644144296646118,
  0.2658441662788391,
  0.2613285779953003,
  0.2603180706501007,
  0.27520254254341125,
  0.2613944709300995,
  0.2563892900943756,
  0.2577013075351715,
  0.2591830790042877,
  0.2598555088043213,
  0.2595157027244568,
  0.25910502672195435,
  0.25574320554733276,
  0.25319087505340576,
  0.260791152715683,
  0.24858547747135162,
  0.25500762462615967,
  0.25515294075012207,
  0.25403982400894165,
  0.2598976492881775,
  0.2583824396133423,
  0.2632540762424469,
  0.2510298192501068,
  0.2561311423778534,
  0.2588464617729187,
  0.2687374949455261,
  0.25483793020248413,
  0.262948602437973,
  0.25933700799942017,
  0.25103336572647095,
  0.25587642192840576,
  0.2505052387714386,
  0.25811439752578735,
  0.2538105249404907,
  0.2471073418855667,
  0.2569088339805603,
  0.2472480833530426,
  0.2529389262199402,
  0.2527693808078766,
  0.24996906518936157,
  0.24836406111717224,
  0.23984211683273315,
  0.2408713698387146,
  0.24250172078609467,
  0.23842118680477142,
  0.2426394373178482,
  0.23827604949474335,
  0.25016817450523376,
  0.2500021457672119,
  0.24978753924369812,
  0.24619396030902863,
  0.25177377462387085,
  0.24281901121139526,
  0.2421303689479828,
  0.2514854073524475,
  0.2474016696214676,
  0.24335677921772003,
  0.24087408185005188,
  0.24894101917743683,
  0.2387939840555191,
  0.23864150047302246,
  0.23954857885837555,
  0.2294805496931076,
  0.2372426837682724,
  0.23932109773159027,
  0.24050480127334595,
  0.24183198809623718,
  0.22251001000404358,
  0.24370506405830383,
  0.23371775448322296,
  0.22908315062522888,
  0.2349146604537964,
  0.23453658819198608,
  0.24102143943309784,
  0.24061177670955658,
  0.2399114966392517,
  0.22236791253089905,
  0.22889329493045807,
  0.2235965132713318,
  0.22806645929813385,
  0.23613137006759644,
  0.22859539091587067,
  0.22299905121326447,
  0.22353020310401917,
  0.2233947217464447,
  0.23080351948738098,
  0.2207554429769516,
  0.2248399704694748,
  0.23469765484333038,
  0.24044227600097656,
  0.23407331109046936,
  0.23817797005176544,
  0.22683799266815186,
  0.23795877397060394,
  0.22966112196445465,
  0.2364330291748047,
  0.2289617955684662,
  0.2293146252632141,
  0.240973562002182,
  0.22396549582481384,
  0.22083498537540436,
  0.22857844829559326,
  0.23279449343681335,
  0.22676125168800354,
  0.2284984588623047,
  0.22064588963985443,
  0.22845393419265747,
  0.22452445328235626,
  0.2232043594121933,
  0.21870170533657074,
  0.21818529069423676,
  0.22294674813747406,
  0.21279694139957428,
  0.2219504415988922,
  0.21449314057826996,
  0.22552481293678284,
  0.2223050445318222,
  0.21873681247234344,
  0.2246164232492447,
  0.2326812446117401,
  0.2389463484287262,
  0.21413151919841766,
  0.22594746947288513,
  0.2187928408384323,
  0.21800284087657928,
  0.22038261592388153,
  0.2162681519985199,
  0.22675339877605438,
  0.22522716224193573,
  0.21451200544834137,
  0.22110554575920105,
  0.21493656933307648,
  0.21585798263549805,
  0.21636387705802917,
  0.2128986269235611,
  0.21334321796894073,
  0.21740977466106415,
  0.2234734296798706,
  0.2173081785440445,
  0.20895090699195862,
  0.21430571377277374,
  0.2139214277267456,
  0.20754414796829224,
  0.20025573670864105,
  0.20266824960708618,
  0.20841532945632935,
  0.20986753702163696,
  0.21976038813591003,
  0.2133939415216446,
  0.21327683329582214,
  0.21042278409004211,
  0.2174910604953766,
  0.2031238079071045,
  0.2087579220533371,
  0.22467516362667084,
  0.2109634280204773,
  0.21807287633419037,
  0.20230872929096222,
  0.21598617732524872,
  0.20520059764385223,
  0.2105853110551834,
  0.20530952513217926,
  0.20963090658187866,
  0.2091817408800125,
  0.21482594311237335,
  0.20363952219486237,
  0.21090903878211975,
  0.20808163285255432,
  0.21393385529518127,
  0.2053212821483612,
  0.20793546736240387,
  0.20869262516498566,
  0.2038881480693817,
  0.20148812234401703,
  0.20678400993347168,
  0.2016521692276001,
  0.1988832652568817,
  0.20601311326026917,
  0.20145519077777863,
  0.20654885470867157,
  0.19432739913463593,
  0.20745471119880676,
  0.20862524211406708,
  0.20736469328403473,
  0.19721248745918274,
  0.2001672089099884,
  0.19627957046031952,
  0.1984492838382721,
  0.1976555436849594,
  0.2008654773235321,
  0.20449182391166687,
  0.19877050817012787,
  0.1994733065366745,
  0.19892695546150208,
  0.19405865669250488,
  0.19843243062496185,
  0.1944114714860916,
  0.20744971930980682,
  0.21952472627162933,
  0.21017338335514069,
  0.19593557715415955,
  0.20786722004413605,
  0.20323272049427032,
  0.19725286960601807,
  0.1933230757713318,
  0.19005897641181946,
  0.19716624915599823,
  0.19252745807170868,
  0.1996203362941742,
  0.19900104403495789,
  0.22012199461460114,
  0.2581161856651306,
  0.22352834045886993,
  0.2140406221151352,
  0.21885794401168823,
  0.22142982482910156,
  0.21779243648052216,
  0.21076074242591858,
  0.21794138848781586,
  0.20788148045539856,
  0.2171066701412201,
  0.20392106473445892,
  0.19915424287319183,
  0.20818084478378296,
  0.20057497918605804,
  0.20251858234405518,
  0.20249681174755096,
  0.2008625715970993,
  0.2058323323726654,
  0.2043239027261734,
  0.20217758417129517,
  0.20389819145202637,
  0.19232414662837982,
  0.19887574017047882,
  0.19850556552410126,
  0.1996101438999176,
  0.19786398112773895,
  0.19199374318122864,
  0.1993284970521927,
  0.20599418878555298,
  0.19926069676876068,
  0.1916215419769287,
  0.1975816786289215,
  0.19291581213474274,
  0.1905578076839447,
  0.19083760678768158,
  0.18755608797073364,
  0.18798723816871643,
  0.18716400861740112,
  0.19409620761871338,
  0.20034807920455933,
  0.18960680067539215,
  0.1962619125843048,
  0.20322823524475098,
  0.19523559510707855,
  0.18443381786346436,
  0.19398431479930878,
  0.1909874975681305,
  0.18609629571437836,
  0.1946898102760315,
  0.1913384199142456,
  0.20643362402915955,
  0.1949521005153656,
  0.19123664498329163,
  0.1838497370481491,
  0.18660812079906464,
  0.18461096286773682,
  0.18661397695541382,
  0.18976551294326782,
  0.18480026721954346,
  0.17793689668178558,
  0.1781659722328186,
  0.1838829666376114,
  0.18262793123722076,
  0.18729378283023834,
  0.18894410133361816,
  0.18535855412483215,
  0.19693823158740997,
  0.20027552545070648,
  0.18640755116939545,
  0.18393006920814514,
  0.1951894611120224,
  0.18701666593551636,
  0.1907796412706375,
  0.18123017251491547,
  0.18309839069843292,
  0.19709743559360504,
  0.18583784997463226,
  0.18619734048843384,
  0.19776931405067444,
  0.18488292396068573,
  0.18333590030670166,
  0.1814359575510025,
  0.18643620610237122,
  0.18258555233478546,
  0.18077833950519562,
  0.17902496457099915,
  0.1889244168996811,
  0.1873781979084015,
  0.18160974979400635,
  0.1900283396244049,
  0.19054095447063446,
  0.1980971097946167,
  0.19544938206672668,
  0.18798786401748657,
  0.1874459832906723,
  0.18524955213069916,
  0.1820521503686905,
  0.18288931250572205,
  0.17900334298610687,
  0.17588503658771515,
  0.17937831580638885,
  0.18335631489753723,
  0.18025250732898712,
  0.19898121058940887,
  0.18297041952610016,
  0.17932471632957458,
  0.17956602573394775,
  0.1803857386112213,
  0.18078279495239258,
  0.17710860073566437,
  0.19114989042282104,
  0.18843992054462433,
  0.17942889034748077,
  0.17974068224430084,
  0.18010030686855316,
  0.182423934340477,
  0.1864573210477829,
  0.1736323982477188,
  0.18472744524478912,
  0.17868223786354065,
  0.18302668631076813,
  0.1859378069639206,
  0.18136823177337646,
  0.18597248196601868,
  0.1797337383031845,
  0.18020214140415192,
  0.19352877140045166,
  0.18894347548484802,
  0.1860363483428955,
  0.18824951350688934,
  0.20039696991443634,
  0.18787817656993866,
  0.1967320293188095,
  0.19339072704315186],
 'val_loss': [5.928153991699219,
  0.9796890616416931,
  0.7081170082092285,
  0.6896927952766418,
  0.7075843811035156,
  0.6850645542144775,
  0.6707370281219482,
  0.6660599708557129,
  0.6558551788330078,
  0.6582669615745544,
  0.6230719089508057,
  0.6028101444244385,
  0.5759520530700684,
  0.5632521510124207,
  0.5639349222183228,
  0.5287894606590271,
  0.5262847542762756,
  0.5070362091064453,
  0.5011499524116516,
  0.49796977639198303,
  0.48940545320510864,
  0.4737091660499573,
  0.4647310972213745,
  0.45806294679641724,
  0.4536961019039154,
  0.4452142119407654,
  0.4383728504180908,
  0.4360981583595276,
  0.43384474515914917,
  0.422981858253479,
  0.41647353768348694,
  0.4105254113674164,
  0.407187283039093,
  0.4041183292865753,
  0.39593783020973206,
  0.3927224576473236,
  0.39230453968048096,
  0.3903396427631378,
  0.3857283592224121,
  0.3876004219055176,
  0.3886629641056061,
  0.3937278389930725,
  0.3873447775840759,
  0.38189488649368286,
  0.37844544649124146,
  0.3689681887626648,
  0.37588727474212646,
  0.3762274384498596,
  0.3686200678348541,
  0.3679589629173279,
  0.3647975027561188,
  0.37504225969314575,
  0.3652842342853546,
  0.3602341115474701,
  0.3570212125778198,
  0.36297890543937683,
  0.36516129970550537,
  0.3523438274860382,
  0.3521544933319092,
  0.3571932315826416,
  0.35876503586769104,
  0.3492072522640228,
  0.3475629389286041,
  0.349671870470047,
  0.3526822626590729,
  0.34409385919570923,
  0.3424694240093231,
  0.3466188907623291,
  0.3468609154224396,
  0.3399989604949951,
  0.3419966697692871,
  0.3446567952632904,
  0.34459102153778076,
  0.34755581617355347,
  0.3431386947631836,
  0.33914855122566223,
  0.341013640165329,
  0.33203259110450745,
  0.33815136551856995,
  0.33117806911468506,
  0.3348884880542755,
  0.3332735598087311,
  0.3275415599346161,
  0.3358185589313507,
  0.33439475297927856,
  0.3249732255935669,
  0.32272136211395264,
  0.32873594760894775,
  0.32234737277030945,
  0.3202817142009735,
  0.32449010014533997,
  0.32224661111831665,
  0.31974706053733826,
  0.31751686334609985,
  0.31613481044769287,
  0.3218115270137787,
  0.3205270767211914,
  0.35436639189720154,
  0.346415638923645,
  0.31942567229270935,
  0.34247151017189026,
  0.3255688548088074,
  0.3196585476398468,
  0.3213667571544647,
  0.32084837555885315,
  0.3219299912452698,
  0.32005852460861206,
  0.31948956847190857,
  0.3225307762622833,
  0.31630411744117737,
  0.31605151295661926,
  0.3219611942768097,
  0.31749945878982544,
  0.3096415400505066,
  0.3115890622138977,
  0.3161728084087372,
  0.3105861246585846,
  0.3068522810935974,
  0.31016185879707336,
  0.3107181787490845,
  0.3087693750858307,
  0.3079797327518463,
  0.31145724654197693,
  0.30823707580566406,
  0.31065839529037476,
  0.31731560826301575,
  0.30647674202919006,
  0.30848485231399536,
  0.3085707724094391,
  0.30800384283065796,
  0.30612775683403015,
  0.3105716109275818,
  0.3048990070819855,
  0.3137131929397583,
  0.31422144174575806,
  0.334136426448822,
  0.31075310707092285,
  0.3039325475692749,
  0.32152968645095825,
  0.30571213364601135,
  0.3089311122894287,
  0.3112257719039917,
  0.309925377368927,
  0.30809974670410156,
  0.30664947628974915,
  0.30749616026878357,
  0.30574315786361694,
  0.3049294352531433,
  0.3029547929763794,
  0.3054407835006714,
  0.3072882890701294,
  0.3035043776035309,
  0.3079982101917267,
  0.30530089139938354,
  0.31043174862861633,
  0.31181564927101135,
  0.3124611973762512,
  0.3026987612247467,
  0.33238786458969116,
  0.30284878611564636,
  0.3034117817878723,
  0.30609896779060364,
  0.31024038791656494,
  0.30602899193763733,
  0.3085956573486328,
  0.31131061911582947,
  0.3065277934074402,
  0.303491473197937,
  0.3073275089263916,
  0.31438159942626953,
  0.30787837505340576,
  0.31841781735420227,
  0.30229032039642334,
  0.32146888971328735,
  0.31265127658843994,
  0.30835068225860596,
  0.3087196350097656,
  0.3188382387161255,
  0.3258126676082611,
  0.3085673451423645,
  0.3208269774913788,
  0.3124592900276184,
  0.30447280406951904,
  0.3085239827632904,
  0.31808385252952576,
  0.30192816257476807,
  0.30984270572662354,
  0.31346336007118225,
  0.3033254146575928,
  0.3132953643798828,
  0.30607283115386963,
  0.31003913283348083,
  0.3144822418689728,
  0.2997160255908966,
  0.3111092448234558,
  0.30715757608413696,
  0.30300667881965637,
  0.31933578848838806,
  0.3041328191757202,
  0.3035898208618164,
  0.31283679604530334,
  0.3123726546764374,
  0.3293689787387848,
  0.30643585324287415,
  0.3035862445831299,
  0.3208983838558197,
  0.29994550347328186,
  0.3045920431613922,
  0.32259151339530945,
  0.3038416802883148,
  0.30163678526878357,
  0.3197600543498993,
  0.3034910261631012,
  0.30492275953292847,
  0.31411829590797424,
  0.3078364133834839,
  0.3017064929008484,
  0.30074912309646606,
  0.3136908710002899,
  0.3198886215686798,
  0.3025868833065033,
  0.31615638732910156,
  0.3081730008125305,
  0.30559438467025757,
  0.305568128824234,
  0.3119513690471649,
  0.3096331059932709,
  0.30670589208602905,
  0.32333967089653015,
  0.3033856451511383,
  0.30342260003089905,
  0.3103187680244446,
  0.30396780371665955,
  0.3004934787750244,
  0.31466466188430786,
  0.3127114176750183,
  0.3105451464653015,
  0.303160160779953,
  0.31093621253967285,
  0.3107582926750183,
  0.31130319833755493,
  0.30275219678878784,
  0.3250720798969269,
  0.3235127627849579,
  0.31415656208992004,
  0.3121643364429474,
  0.30505645275115967,
  0.3120763301849365,
  0.32457244396209717,
  0.29673582315444946,
  0.3050324320793152,
  0.3339698612689972,
  0.3179730176925659,
  0.32536745071411133,
  0.31619992852211,
  0.301304429769516,
  0.32203900814056396,
  0.31845176219940186,
  0.30164632201194763,
  0.31589823961257935,
  0.31723061203956604,
  0.3037141263484955,
  0.3197694718837738,
  0.31277939677238464,
  0.30669966340065,
  0.31960734724998474,
  0.3077067732810974,
  0.31346023082733154,
  0.3224106729030609,
  0.3046611249446869,
  0.33815592527389526,
  0.3035154342651367,
  0.31266868114471436,
  0.3377911150455475,
  0.305948406457901,
  0.3010398745536804,
  0.3186132311820984,
  0.2958538830280304,
  0.3035607933998108,
  0.32120782136917114,
  0.29821017384529114,
  0.32172536849975586,
  0.3160853087902069,
  0.32333099842071533,
  0.30568423867225647,
  0.3106362223625183,
  0.3269459903240204,
  0.3028959631919861,
  0.3090864419937134,
  0.3249923586845398,
  0.3024064004421234,
  0.33083224296569824,
  0.31752875447273254,
  0.306514710187912,
  0.309935986995697,
  0.3204203248023987,
  0.3129964768886566,
  0.3139604330062866,
  0.30628326535224915,
  0.3159661293029785,
  0.3296533524990082,
  0.31291836500167847,
  0.34277743101119995,
  0.30911245942115784,
  0.3178987503051758,
  0.33114179968833923,
  0.30454137921333313,
  0.3177202045917511,
  0.33564499020576477,
  0.3117239475250244,
  0.31188344955444336,
  0.3240053951740265,
  0.310838520526886,
  0.3251047730445862,
  0.32192468643188477,
  0.3096470534801483,
  0.32259508967399597,
  0.34217172861099243,
  0.3035508692264557,
  0.3246612250804901,
  0.3215120732784271,
  0.3161231577396393,
  0.3396022915840149,
  0.3154488205909729,
  0.31446361541748047,
  0.33332371711730957,
  0.3106623589992523,
  0.3153768479824066,
  0.33117303252220154,
  0.3187016546726227,
  0.3166566789150238,
  0.3260590732097626,
  0.3180225193500519,
  0.3295433819293976,
  0.33041903376579285,
  0.30519822239875793,
  0.34676265716552734,
  0.31023865938186646,
  0.3254368305206299,
  0.31324681639671326,
  0.32638654112815857,
  0.3267222046852112,
  0.32582011818885803,
  0.3274748921394348,
  0.3195098340511322,
  0.3377722501754761,
  0.3114123046398163,
  0.33334726095199585,
  0.3261384069919586,
  0.3262743651866913,
  0.33499830961227417,
  0.315218061208725,
  0.3758125305175781,
  0.30874210596084595,
  0.32732388377189636,
  0.3459210991859436,
  0.307142436504364,
  0.3192422688007355,
  0.3293221890926361,
  0.3183858096599579,
  0.31944984197616577,
  0.3301301896572113,
  0.31391653418540955,
  0.349305123090744,
  0.3312806785106659,
  0.37796926498413086,
  0.34337466955184937,
  0.32094278931617737,
  0.32258448004722595,
  0.34529465436935425,
  0.3055105209350586,
  0.3234868049621582,
  0.32780206203460693,
  0.31512388586997986,
  0.31419453024864197,
  0.32067355513572693,
  0.3158472180366516,
  0.3242262601852417,
  0.324863463640213,
  0.32199591398239136,
  0.3259901702404022,
  0.3265395760536194,
  0.3333292007446289,
  0.3199704885482788,
  0.3163341283798218,
  0.33177450299263,
  0.3207225799560547,
  0.3156781494617462,
  0.3498542606830597,

In [23]:
model.evaluate(test_data)

{'loss': 0.34334754943847656, 'roc_auc': 0.948}

Test multiple splits

In [20]:
import numpy as np
aucs = []
for i in range(5):
    seed_everything(i)
    model.reset()
    train_data, val_data, test_data = data.split_data(task="link_prediction",
                                                  negative_sampler=sampler,
                                                  supervision_edge_type=supervision_edge_type,
                                                  disjoint_train_ratio=0.2, 
                                                  num_val=0.1,
                                                  num_test=0.1)
    splits = {"train":train_data, "val":val_data, "test":test_data}
    model.train(splits, sampler,supervision_edge_type, epochs=500)
    aucs.append(model.evaluate(test_data)["roc_auc"])

print(aucs)
print(np.mean(aucs))

[0.949, 0.949, 0.941, 0.948, 0.95]
0.9474